### ISSUE TITLE
pip install failure

### ISSUE THREAD

**Issue by kdk411** [mrzv/dionysus#16]
Hi,

I am trying to pip install within my virtualenv, but it failed to build with the following error:

```
[IDH] [ddkim1@q1prphtcs18 TDA_analysis]$ pip install --verbose dionysus
Collecting dionysus
  1 location(s) to search for versions of dionysus:
  * https://pypi.python.org/simple/dionysus/
  Getting page https://pypi.python.org/simple/dionysus/
  Looking up "https://pypi.python.org/simple/dionysus/" in the cache
  Returning cached "301 Moved Permanently" response (ignoring date and etag information)
  Looking up "https://pypi.org/simple/dionysus/" in the cache
  Current age based on date: 667
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  Starting new HTTPS connection (1): pypi.org
  "GET /simple/dionysus/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/dionysus/
    Found link https://files.pythonhosted.org/packages/cf/58/4f56cbc4125ae89f69b2862107014e06fc6a12a36b7fb6e94ad95eab36c3/dionysus-2.0.1.tar.gz#sha256=040e45d9bd415dfdc02dd9bf257affe9e865c029dbfef9d703144e6cf7311fcf (from https://pypi.org/simple/dionysus/), version: 2.0.1
    Found link https://files.pythonhosted.org/packages/47/5f/fdff2b2868de745a07614077f303bb45316644bc032ebfaca1436d728440/dionysus-2.0.2.tar.gz#sha256=78c24da06fd273f0103ad4cb86331f5f4518d7f0445e2cecd0e325ca1a2d011f (from https://pypi.org/simple/dionysus/), version: 2.0.2
    Found link https://files.pythonhosted.org/packages/20/77/e6395687eb442e7dcb37ceb3ad5646f222ac74739b0aa186189a22085ee7/dionysus-2.0.3.tar.gz#sha256=cdd44b3dfd7199290f28af1b6d3fdd61167db231601330a9b73cad083a86366d (from https://pypi.org/simple/dionysus/), version: 2.0.3
    Found link https://files.pythonhosted.org/packages/e7/7c/9e5f6911dfac70ac62a544155f9e3b4436f20a8c4e8559aeb492381549c1/dionysus-2.0.4.tar.gz#sha256=e411396c63aa6838e414c18979d4d90a28fcc60ae1660389e6b777a43479bf40 (from https://pypi.org/simple/dionysus/), version: 2.0.4
  Using version 2.0.4 (newest of versions: 2.0.1, 2.0.2, 2.0.3, 2.0.4)
  Looking up "https://files.pythonhosted.org/packages/e7/7c/9e5f6911dfac70ac62a544155f9e3b4436f20a8c4e8559aeb492381549c1/dionysus-2.0.4.tar.gz" in the cache
  Current age based on date: 667
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 667
  Using cached https://files.pythonhosted.org/packages/e7/7c/9e5f6911dfac70ac62a544155f9e3b4436f20a8c4e8559aeb492381549c1/dionysus-2.0.4.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/e7/7c/9e5f6911dfac70ac62a544155f9e3b4436f20a8c4e8559aeb492381549c1/dionysus-2.0.4.tar.gz#sha256=e411396c63aa6838e414c18979d4d90a28fcc60ae1660389e6b777a43479bf40 (from https://pypi.org/simple/dionysus/)
  Running setup.py (path:/tmp/pip-build-Cy8XoO/dionysus/setup.py) egg_info for package dionysus
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/dionysus.egg-info
    writing pip-egg-info/dionysus.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/dionysus.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/dionysus.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/dionysus.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/dionysus.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory './.hg'
    warning: no previously-included files matching '*' found under directory './doc/_build'
    warning: no previously-included files matching '*' found under directory './dist'
    warning: no previously-included files found matching '.hgignore'
    warning: no previously-included files found matching '.hgsubtree'
    warning: no previously-included files found matching 'tags'
    warning: no previously-included files matching '*.orig' found under directory '.'
    writing manifest file 'pip-egg-info/dionysus.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-Cy8XoO/dionysus has version 2.0.4, which satisfies requirement dionysus from https://files.pythonhosted.org/packages/e7/7c/9e5f6911dfac70ac62a544155f9e3b4436f20a8c4e8559aeb492381549c1/dionysus-2.0.4.tar.gz#sha256=e411396c63aa6838e414c18979d4d90a28fcc60ae1660389e6b777a43479bf40
Building wheels for collected packages: dionysus
  Running setup.py bdist_wheel for dionysus ...   Destination directory: /tmp/tmpssbuGmpip-wheel-
  Running command /rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/IDH_Prediction/IDH/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Cy8XoO/dionysus/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpssbuGmpip-wheel- --python-tag cp27
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/dionysus
  copying bindings/python/dionysus/plot.py -> build/lib.linux-x86_64-2.7/dionysus
  copying bindings/python/dionysus/_version.py -> build/lib.linux-x86_64-2.7/dionysus
  copying bindings/python/dionysus/__init__.py -> build/lib.linux-x86_64-2.7/dionysus
  running build_ext
  -- The C compiler identification is GNU 4.8.5
  -- The CXX compiler identification is GNU 4.8.5
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Could NOT find Boost
  -- Found PythonInterp: /rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/IDH_Prediction/IDH/bin/python2.7 (found version "2.7.13")
  -- Found PythonLibs: /software/x86_64/python/2.7.13/lib/libpython2.7.so
  -- Performing Test HAS_CPP14_FLAG
  **-- Performing Test HAS_CPP14_FLAG - Failed**
  -- Performing Test HAS_CPP11_FLAG
  -- Performing Test HAS_CPP11_FLAG - Success
  -- pybind11 v2.2.0
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- LTO enabled
  **CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  Boost_INCLUDE_DIR (ADVANCED)
     used as include directory in directory /tmp/pip-build-Cy8XoO/dionysus/bindings/python
     used as include directory in directory /tmp/pip-build-Cy8XoO/dionysus/bindings/python**

  **-- Configuring incomplete, errors occurred!**
  See also "/tmp/pip-build-Cy8XoO/dionysus/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-build-Cy8XoO/dionysus/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-Cy8XoO/dionysus/setup.py", line 97, in <module>
      zip_safe=False,
    File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/IDH_Prediction/IDH/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-Cy8XoO/dionysus/setup.py", line 39, in run
      self.build_extension(ext)
    File "/tmp/pip-build-Cy8XoO/dionysus/setup.py", line 64, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/software/x86_64/python/2.7.13/lib/python2.7/subprocess.py", line 186, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-build-Cy8XoO/dionysus', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-build-Cy8XoO/dionysus/build/lib.linux-x86_64-2.7', '-DPYTHON_EXECUTABLE=/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/IDH_Prediction/IDH/bin/python2.7', '-Dbuild_examples=OFF', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
error
  **Failed building wheel for dionysus**
  Running setup.py clean for dionysus
  Running command /rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/IDH_Prediction/IDH/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Cy8XoO/dionysus/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all
  running clean
  removing 'build/temp.linux-x86_64-2.7' (and everything under it)
  removing 'build/lib.linux-x86_64-2.7' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-2.7' does not exist -- can't clean it
  removing 'build'
**Failed to build dionysus**
Installing collected packages: dionysus
  Running setup.py install for dionysus ...     Running command /rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/IDH_Prediction/IDH/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Cy8XoO/dionysus/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-283Fmb-record/install-record.txt --single-version-externally-managed --compile --install-headers /rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/IDH_Prediction/IDH/include/site/python2.7/dionysus
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/dionysus
    copying bindings/python/dionysus/plot.py -> build/lib.linux-x86_64-2.7/dionysus
    copying bindings/python/dionysus/_version.py -> build/lib.linux-x86_64-2.7/dionysus
    copying bindings/python/dionysus/__init__.py -> build/lib.linux-x86_64-2.7/dionysus
    running build_ext
    -- The C compiler identification is GNU 4.8.5
    -- The CXX compiler identification is GNU 4.8.5
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Could NOT find Boost
    -- Found PythonInterp: /rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/IDH_Prediction/IDH/bin/python2.7 (found version "2.7.13")
    -- Found PythonLibs: /software/x86_64/python/2.7.13/lib/libpython2.7.so
    -- Performing Test HAS_CPP14_FLAG
    **-- Performing Test HAS_CPP14_FLAG - Failed**
    -- Performing Test HAS_CPP11_FLAG
    -- Performing Test HAS_CPP11_FLAG - Success
    -- pybind11 v2.2.0
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    **CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    Boost_INCLUDE_DIR (ADVANCED)
       used as include directory in directory /tmp/pip-build-Cy8XoO/dionysus/bindings/python
       used as include directory in directory /tmp/pip-build-Cy8XoO/dionysus/bindings/python**

    **-- Configuring incomplete, errors occurred!**
    See also "/tmp/pip-build-Cy8XoO/dionysus/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-build-Cy8XoO/dionysus/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Cy8XoO/dionysus/setup.py", line 97, in <module>
        zip_safe=False,
      File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/software/x86_64/python/2.7.13/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/software/x86_64/python/2.7.13/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-Cy8XoO/dionysus/setup.py", line 39, in run
        self.build_extension(ext)
      File "/tmp/pip-build-Cy8XoO/dionysus/setup.py", line 64, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/software/x86_64/python/2.7.13/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    **subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-build-Cy8XoO/dionysus', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-build-Cy8XoO/dionysus/build/lib.linux-x86_64-2.7', '-DPYTHON_EXECUTABLE=/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/IDH_Prediction/IDH/bin/python2.7', '-Dbuild_examples=OFF', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
error**
Cleaning up...
  Removing source in /tmp/pip-build-Cy8XoO/dionysus
Command "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/IDH_Prediction/IDH/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Cy8XoO/dionysus/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-283Fmb-record/install-record.txt --single-version-externally-managed --compile --install-headers /rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/IDH_Prediction/IDH/include/site/python2.7/dionysus" failed with error code 1 in /tmp/pip-build-Cy8XoO/dionysus/
Exception information:
Traceback (most recent call last):
  File "/software/x86_64/python/2.7.13/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/software/x86_64/python/2.7.13/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/software/x86_64/python/2.7.13/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/software/x86_64/python/2.7.13/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/software/x86_64/python/2.7.13/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/IDH_Prediction/IDH/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Cy8XoO/dionysus/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-283Fmb-record/install-record.txt --single-version-externally-managed --compile --install-headers /rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/IDH_Prediction/IDH/include/site/python2.7/dionysus" failed with error code 1 in /tmp/pip-build-Cy8XoO/dionysus/
`
```

I think the issue is that when building, it is using certain variables in the project, but somehow they are not connected correctly...?  as below?
```
**CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  Boost_INCLUDE_DIR (ADVANCED)
     used as include directory in directory /tmp/pip-build-Cy8XoO/dionysus/bindings/python
     used as include directory in directory /tmp/pip-build-Cy8XoO/dionysus/bindings/python**
```

Any suggestions to solve this issue?

**Comment by mrzv** [comment]
It looks like you are missing Boost. You should be able to install it using your system's package manger.
